# Generated by Django 4.1.1 on 2022-11-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='Item title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Item description')),
                ('price', models.PositiveIntegerField(verbose_name='Item price')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('loc_district', models.CharField(max_length=50, verbose_name='District')),
                ('loc_city', models.CharField(max_length=50, verbose_name='City')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
