# Generated by Django 4.1.1 on 2022-11-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('login', models.CharField(max_length=100, unique=True, verbose_name='Customer login')),
                ('password', models.CharField(max_length=100, verbose_name='Customer password')),
                ('first_name', models.CharField(max_length=20, verbose_name='Customer first name')),
                ('surname', models.CharField(max_length=20, verbose_name='Customer surname')),
                ('email', models.EmailField(max_length=254, verbose_name='Customer email')),
                ('phone', models.PositiveIntegerField(max_length=12, verbose_name='Customer phone number')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
